[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source $HOME/.vim/plugins/vim-easymotion.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = 'source $HOME/.vim/plugins/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = 'source $HOME/.vim/plugins/vim-multiple-cursors.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = 'source $HOME/.vim/plugins/vim-over.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source $HOME/.vim/plugins/caw.vim'

[[plugins]]
repo = 'thinca/vim-splash'
hook_add = 'source $HOME/.vim/plugins/vim-splash.vim'
