[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
hook_add = 'source ${HOME}/.vim/plugins/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
hook_add = 'source ${HOME}/.vim/plugins/neosnippet.vim'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_add = 'source ${HOME}/.vim/plugins/vim-javascript.vim'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = 'source ${HOME}/.vim/plugins/vim-jsx.vim'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = 'source ${HOME}/.vim/plugins/vim-json.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

