[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = 'source $HOME/.vim/plugins/vim-json.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'eruby', 'php', 'vue']
hook_source = 'source $HOME/.vim/plugins/emmet-vim.vim'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_source = 'source $HOME/.vim/plugins/vim-jsx.vim'

[[plugins]]
repo = 'nelsyeung/twig.vim'
on_ft = 'twig'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'eruby']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_source = 'source $HOME/.vim/plugins/vim-javascript.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = 'source $HOME/.vim/plugins/deoplete.vim'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'
